export const videos = [
  { id: 'QZexS5JDKpc', title: 'What are you passing down from Generation to Generation?' },
  { id: '_djQXuMniig', title: 'ARE YOU PASSING DOWN PAIN?' },
  { id: '9-OiqitupIU', title: 'How to Lead Without Losing Yourself: Stay Rooted in Christ' },
  { id: 'RjPN-cDn4n0', title: 'Leadership Boundaries Are Not Selfish—They’re Stewardship' },
  { id: 'cdCBtTdeMxk', title: 'You Were Never Called to Carry Everyone: Leadership Burnout and Boundaries' },
  { id: 'ABTYwSKfa3U', title: 'You Can Be Successful and Still Be Falling Apart?' },
  { id: 'Hy-mRWM6zi0', title: 'Why Strong Leaders Feel Empty? High-Functioning Burnout' },
  { id: 'mFIWUEuHgv8', title: 'Why Do I Keep Thinking Negative Thoughts?' },
  { id: 'XRdf7spY1SE', title: 'Plant • Water • Grow | How Open Arms Initiative Brings Hope to Children & Families' },
  { id: 'GudSud43K-I', title: 'Every Home Deserves Healing — The Mission of Open Arms Mental Health Initiative' },
  { id: 'IkwbPsOvdHU', title: 'The Heart Behind Healing: How Open Arms Initiative Supports Children & Families' },
  { id: 'T45jLyOXKU0', title: 'Healing takes time. You don’t have to do it alone. | Open Arms Initiative' },
  { id: 'QtPdo6l_FRQ', title: 'Therapy is where the real work happens | Open Arms Initiative' },
  { id: 'VUHx9R1YPUI', title: 'Time doesn’t heal what you never face. | Open Arms Initiative' },
  { id: 'EOWU2RE6tFg', title: 'Trauma is the Most Misdiagnosed Issue | Open Arms Initiative' },
  { id: 'n1XNgzaXVvI', title: 'A Safe Space for Healing & Growth | Open Arms Initiative' },
  { id: 'Gsh5ygimHSE', title: 'How To Choose The Right Therapist For You | Open Arms Initiative' },
  { id: 'naaqiXpWEJs', title: 'Don\'t Quit Before Therapy Starts Working | Open Arms Initiative' },
];
