import Link from 'next/link';
import ScrollReveal from '@/components/ScrollReveal';

export const metadata = { title: 'Marriage Counseling Oklahoma City | Open Arms Initiative', description: 'Find compassionate marriage counseling in Oklahoma City. Open Arms Initiative helps couples improve communication, navigate conflict, and rebuild connection.' };

const trustIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20.5s-6.5-4-9-8.2C1.2 8.8 3 5.5 6.2 5.5c1.9 0 3.2 1 3.8 2.1.6-1.1 1.9-2.1 3.8-2.1 3.2 0 5 3.3 3.2 6.8-2.5 4.2-9 8.2-9 8.2Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3.5 19 6v6c0 4.5-3 7.5-7 8.5-4-1-7-4-7-8.5V6l7-2.5Z" /><path d="m9.3 12 1.9 1.9 3.6-3.9" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="8" r="3.2" /><path d="M3.5 19c.6-3.4 2.7-5.3 5.5-5.3s4.9 1.9 5.5 5.3" /><path d="M15.2 5.2A3.2 3.2 0 0 1 15.7 11.5" /><path d="M16.8 13.9c2.4.4 4 2.2 4.5 5.1" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="12" rx="1.5" /><path d="M1.5 20h21" /><path d="M8.5 9.5h4M8.5 12.5h7" /></svg>,
];

const stepIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="7.5" r="2.8" /><path d="M2.5 19c.5-3.4 2.5-5.3 5.5-5.3s5 1.9 5.5 5.3" /><path d="M14.5 5c1.3.5 2.2 1.7 2.2 3.1s-.9 2.6-2.2 3.1" /><path d="M15 14c2 .3 3.4 1.9 3.8 5" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M9 19.5v-2.3c-2.3-1.1-3.8-3.2-3.8-6A6.8 6.8 0 0 1 12 4.4a6.8 6.8 0 0 1 6.8 6.8c0 2.8-1.5 4.9-3.8 6v2.3Z" /><path d="M9 19.5h6" /><path d="M9.8 22h4.4" /><path d="M12 8.4a2.3 2.3 0 0 0-2.3 2.3c0 1.6 2.3 3 2.3 3s2.3-1.4 2.3-3A2.3 2.3 0 0 0 12 8.4Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="10.2" cy="10.2" r="6.2" /><path d="m19.5 19.5-4.1-4.1" /><path d="M7.3 10.2h1.5M10.2 7.3v1.5M10.2 12.1v1.5M12.1 10.2h1.5" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12h15.5" /><path d="m13.5 6 6 6-6 6" /></svg>,
];

const challengeIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5.5h8a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H8l-3.2 2.6v-2.6H3a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2Z" /><path d="M15.5 8h2.8a2 2 0 0 1 2 2v3.5a2 2 0 0 1-2 2h-1.1v2.3L14.8 15.5H12a2 2 0 0 1-2-2v-.3" /><path d="m9.5 5.5-1.8 3.3h2.6L8.5 12.1" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12a8 8 0 0 1 13.66-5.66L20 8" /><path d="M20 4v4h-4" /><path d="M20 12a8 8 0 0 1-13.66 5.66L4 16" /><path d="M4 20v-4h4" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="6" cy="8" r="2.6" /><circle cx="18" cy="8" r="2.6" /><path d="M2.2 19c.4-3 2-4.8 3.8-4.8s3.4 1.8 3.8 4.8" /><path d="M14.2 19c.4-3 2-4.8 3.8-4.8s3.4 1.8 3.8 4.8" /><path d="M9 12.5h6" strokeDasharray="2.4 2.4" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20.2s-7-4.3-9.3-8.7C1.2 8 3 4.5 6.4 4.5c2 0 3.3 1.1 4 2.3" /><path d="M17.6 4.5c-1.6 0-2.8.7-3.6 1.7l-2.4 3 2 2-1.6 2 2 2" /><path d="M17.6 4.5c3.4 0 5.2 3.5 3.7 6.9-1 2.2-2.8 4.2-4.6 5.8" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2.5v19" /><path d="M12 6 4 8.3a1 1 0 0 0 0 1.9L12 12" /><path d="M12 12l7.3-2.1a1 1 0 0 0 0-1.9L12 6" /><path d="M7 16.5h4M7 19h7" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 12 4 6" /><path d="M4 6h5.5M4 6v5.5" /><path d="M12 12l8 6" /><path d="M20 18h-5.5M20 18v-5.5" /></svg>,
];

const approachIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="7" cy="7.5" r="2.6" /><circle cx="17" cy="7.5" r="2.6" /><path d="M2 19c.5-3.2 2.3-5 5-5s4.5 1.8 5 5" /><path d="M12 19c.5-3.2 2.3-5 5-5s4.5 1.8 5 5" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="10.5" cy="10.5" r="6.5" /><path d="m20 20-4.3-4.3" /><path d="M7.5 10.5h6M10.5 7.5v6" strokeDasharray="1.6 2.4" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M14.5 6.5 17 4a3 3 0 0 1 4 4l-2.5 2.5" /><path d="m9 12-6 6a2.1 2.1 0 0 0 3 3l6-6" /><path d="m12.5 8.5 3 3" /><path d="m14 4 2 2M18 8l2 2" /></svg>,
];

const challenges = [['Communication Breakdowns','You talk, but neither person feels truly heard or understood.'],['Recurring Conflict','The subject may change, but somehow you keep having the same argument.'],['Emotional Distance','You may share a home and a life while feeling increasingly disconnected from each other.'],['Trust & Relationship Hurt','Past experiences or unresolved hurt may make it difficult to feel secure and connected.'],['Life Transitions','Parenthood, career changes, relocation, caregiving, financial stress, and other transitions can place pressure on a relationship.'],['Different Needs & Expectations','Differences around affection, responsibilities, priorities, boundaries, or the future can create frustration and resentment.']];
const faqs = [['How do we know if we need couples counseling?', 'You don’t need to wait until your relationship reaches a breaking point. Couples may consider counseling when communication has become difficult, the same conflicts keep returning, emotional distance is growing, trust has been affected, or they want professional support navigating a major transition.'],['What happens during marriage counseling?', 'Your therapist will learn about your relationship, concerns, communication patterns, and goals. Counseling provides a structured environment where both partners can discuss difficult issues, understand each other’s perspectives, and work toward healthier ways of communicating and relating.'],['Will the therapist take one person’s side?', 'Couples counseling is not intended to determine a winner or assign blame. The therapist’s role is to support the therapeutic process and help both partners explore the patterns, concerns, and experiences affecting the relationship.'],['Can couples therapy help us communicate better?', 'Improving communication is a common focus of couples therapy. Counseling can help partners recognize communication patterns, express needs more clearly, listen more effectively, and approach disagreements in healthier ways.'],['Do you offer couples therapy in Oklahoma City?', <>Yes. Open Arms Initiative provides <strong>Couples Therapy in OKC</strong> for partners seeking support with communication, recurring conflict, emotional distance, trust concerns, relationship transitions, and other challenges.</>],['Should we consider counseling even if we aren’t married?', 'Yes. Couples counseling can be relevant to committed partners regardless of marital status. Your therapist can discuss your concerns and determine whether the service is appropriate for your circumstances.']];

export default function MarriageCounselingPage() { return <main className="marriage-page">
  <ScrollReveal />
  <section className="marriage-hero-outer"><div className="marriage-hero-bg"><img src="/m5.png" alt="Couple in marriage counseling" /><div className="marriage-container marriage-hero-content"><div className="marriage-hero-copy"><p className="marriage-kicker">RECONNECT. UNDERSTAND. GROW TOGETHER.</p><h1>Marriage Counseling<br />in Oklahoma City</h1><i /><p className="marriage-lead">When You Still Care, But Connecting Feels Hard</p><p>You may love each other deeply and still feel distant. Conversations may turn into arguments. Silence may have replaced connection. Trust may feel fragile, or you may simply wonder how two people who once felt so close became so disconnected.</p><p>You don&apos;t have to know how to fix everything before asking for help.</p><p>At Open Arms Initiative, we provide compassionate <strong>Marriage Counseling in Oklahoma City</strong> to help couples understand what is happening beneath the conflict, communicate more openly, and find a healthier way forward—together.</p><div className="marriage-actions"><Link className="marriage-btn marriage-solid" href="/contact">Request an Appointment</Link><a className="marriage-btn marriage-outline" href="#approach">Explore Our Approach</a></div></div></div></div></section>
  <section className="marriage-trust-section"><div className="marriage-container marriage-trust reveal reveal-from-bottom">{['Compassionate Support','Safe & Confidential','Experienced Therapists','In-Person & Online'].map((x,i)=><div key={x}><b>{trustIcons[i]}</b>{x}</div>)}</div></section>
  <section className="marriage-section marriage-love"><div className="marriage-container reveal reveal-from-bottom"><h2>Sometimes Love Is Still There, It Just Feels Hard to Reach</h2><p>Relationship struggles don&apos;t always begin with one major event. Sometimes distance grows quietly. The conversations get shorter. Small disagreements become recurring arguments. Affection changes. One person feels unheard while the other feels misunderstood.</p><p>And eventually, you may find yourselves asking: <strong>“How did we get here?”</strong></p><p>Seeking counseling doesn&apos;t mean your relationship has failed. It means you&apos;re willing to look at what&apos;s happening and explore whether something healthier can be built from here.</p></div></section>
  <section className="marriage-section marriage-challenges"><div className="marriage-container reveal reveal-scale-in"><p className="marriage-kicker">WE HELP COUPLES NAVIGATE</p><h2>What Are You Carrying Into Your Relationship?</h2><i className="marriage-challenges-divider"><b /></i><div className="reveal-stagger">{challenges.map(([h,p],i)=><article className="reveal reveal-from-bottom" key={h}><span>{challengeIcons[i]}</span><div><h3>{h}</h3><i className="marriage-challenges-rule" /><p>{p}</p></div></article>)}</div></div></section>
  <section id="approach" className="marriage-section"><div className="marriage-container marriage-place"><div className="reveal reveal-from-left"><p className="marriage-kicker">COUPLES THERAPY OKC</p><h2>A Place to Hear Each Other Again</h2><p>Couples counseling isn&apos;t about deciding who wins the argument. And your therapist isn&apos;t there to choose a side.</p><p>Our <strong>Couples Therapy in OKC</strong> provides space to slow difficult conversations down, understand each person&apos;s experience, recognize unhealthy patterns, and work toward more constructive ways of relating to one another.</p><p>Together, you may work on:</p><ul>{['Communicating more openly','Understanding each other’s needs','Managing disagreements differently','Rebuilding emotional connection','Establishing healthier boundaries','Addressing unresolved hurt','Strengthening trust','Navigating changes as a team'].map(x=><li key={x}>{x}</li>)}</ul><p><strong>The goal isn&apos;t a perfect relationship. It&apos;s a relationship where both people have a better chance of feeling heard, respected, and understood.</strong></p></div><img className="reveal reveal-from-right" src="/mg2.jpg" alt="Couple talking openly during a counseling conversation"/></div></section>
  <section className="marriage-section marriage-bridge"><div className="marriage-container"><div className="reveal reveal-from-bottom"><h2>What If We&apos;ve Already Tried to Fix It Ourselves?</h2><p>Many couples have. You&apos;ve promised to communicate differently. You&apos;ve tried avoiding certain subjects. You&apos;ve had long conversations late at night. Maybe things improved for a while—only for the same patterns to return.</p><p>That doesn&apos;t necessarily mean change isn&apos;t possible. Sometimes couples become caught in patterns that are difficult to recognize while they&apos;re happening.</p><p><strong>Relationship Counseling Services in Oklahoma City</strong> can provide a neutral, structured environment where you can step outside those patterns and begin understanding not only what you&apos;re arguing about, but what may be happening underneath it.</p></div><aside className="reveal reveal-scale-in"><h3>“You don&apos;t have to choose between pretending everything is fine and giving up.”</h3><p>There is space in between. A space where you can ask difficult questions, understand each other more clearly, and decide what moving forward can look like.</p><Link href="/contact" className="marriage-btn marriage-olive">Request a Couples Counseling Appointment</Link></aside></div></section>
  <section className="marriage-section marriage-approach-section"><div className="marriage-container marriage-approach"><div className="reveal reveal-from-right"><h2>Our Approach to Couples Counseling</h2>{[['A Space for Both Partners','Both experiences matter. We create a respectful environment where each partner has room to speak, listen, and better understand the relationship from the other’s perspective.'],['Understanding the Pattern','Instead of focusing only on individual arguments, counseling can help identify recurring communication and relationship patterns contributing to disconnection.'],['Building Practical Skills','Insight matters—but couples also need tools they can use outside therapy. We help couples develop healthier approaches to communication, conflict, boundaries, and emotional connection.']].map(([h,p],i)=><article key={h}><span>{approachIcons[i]}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div><img className="reveal reveal-from-left" src="/mg4.jpg" alt="Group counseling conversation in a warm, welcoming space" /></div></section>
  <section className="marriage-section marriage-expect"><div className="marriage-container"><h2 className="marriage-center reveal reveal-from-bottom">What to Expect</h2><i className="marriage-line-center" /><div className="marriage-steps reveal-stagger">{[['01','Connect','Reach out to Open Arms Initiative and schedule an initial appointment.'],['02','Understand','Your therapist learns about your relationship, current concerns, experiences, and what each of you hopes to gain from counseling.'],['03','Identify the Patterns','Together, you’ll explore communication habits, recurring conflicts, relationship dynamics, and areas where change may be helpful.'],['04','Move Forward','You’ll work toward healthier communication and relationship skills that can support meaningful change beyond the counseling room.']].map(([n,h,p],i)=><article className="reveal reveal-from-bottom" key={n}><span className="marriage-step-badge">{n}</span><span className="marriage-step-icon">{stepIcons[i]}</span><h3>{h}</h3><i /><p>{p}</p></article>)}</div></div></section>
  <section className="marriage-section"><div className="marriage-container"><div className="marriage-faq"><aside className="reveal reveal-from-left"><h2>It&apos;s okay to have questions before asking for help.</h2><p>We&apos;re here to provide answers, guidance, and support so you can take the next step with confidence.</p></aside><div className="reveal reveal-from-right"><h2>Questions Couples Often Ask</h2>{faqs.map(([q,a])=><details key={q} name="marriage-faq-group"><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></div></section>
  <section className="marriage-final"><div className="marriage-container reveal reveal-scale-in"><div><h2>You Don&apos;t Have to Know the Ending to Take the Next Step.</h2><p>Maybe you want to feel close again. Maybe you want conversations to stop becoming battles. Maybe you&apos;re simply trying to understand what happened between you. Whatever brought you here, reaching out can create a place to begin.</p><h3>Hope for the Relationship Can Start With One Conversation.</h3></div><Link href="/contact" className="marriage-btn marriage-light">Request an Appointment</Link></div></section>
</main> }
