/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      { source: '/contact-us', destination: '/contact', permanent: true },
      { source: '/blog', destination: '/blogs', permanent: true },
      { source: '/adult-counseling', destination: '/adult-counseling-oklahoma-city', permanent: true },
      { source: '/child-adolescent-counseling', destination: '/child-counseling-services-oklahoma-city', permanent: true },
      { source: '/family-counseling', destination: '/family-therapy-oklahoma-city', permanent: true },
      { source: '/marriage-couples-therapy', destination: '/marriage-counseling-oklahoma-city', permanent: true },
      { source: '/grief-and-loss-counseling', destination: '/grief-counseling-oklahoma-city', permanent: true },
      { source: '/depression-anxiety-counseling', destination: '/depression-anxiety-counseling-oklahoma', permanent: true },
      { source: '/foster-care-adoption-counseling', destination: '/foster-care', permanent: true },
      { source: '/services/foster-care-adoption-counseling', destination: '/foster-care', permanent: true },
      { source: '/pro-bono-therapy-services', destination: '/pro-bono-counseling-okc', permanent: true },
      { source: '/community-outreach-support-programs', destination: '/services/community-outreach-support', permanent: true },
      { source: '/trauma-informed-care-training', destination: '/trauma-mental-health-training', permanent: true },
      { source: '/training-speaking/trauma-mental-health-training', destination: '/trauma-mental-health-training', permanent: true },
      { source: '/parenting-skills-development', destination: '/parenting-classes-okc', permanent: true },
      { source: '/school-staff-educator-training', destination: '/services/school-staff-educator-training', permanent: true },
      { source: '/anxiety-depression-and-stress-management', destination: '/depression-anxiety-counseling-oklahoma', permanent: true },
      { source: '/mental-health-awareness-human-development', destination: '/trauma-mental-health-training', permanent: true },
      { source: '/churches-faith-based-training', destination: '/services/churches-faith-based-training', permanent: true },
      { source: '/referrals', destination: '/local-referrals', permanent: true },

      // Legacy blog post URLs (previously at site root, now under /blogs/)
      { source: '/the-let-them-theory-a-therapist-s-perspective-on-when-it-helps-and-when-it-doesn-t', destination: '/blogs/the-let-them-theory-a-therapist-s-perspective-on-when-it-helps-and-when-it-doesn-t', permanent: true },
      { source: '/do-you-feel-disconnected-from-your-partner', destination: '/blogs/do-you-feel-disconnected-from-your-partner', permanent: true },
      { source: '/10-signs-your-relationship-could-benefit-from-couples-therapy', destination: '/blogs/10-signs-your-relationship-could-benefit-from-couples-therapy', permanent: true },
      { source: '/can-counseling-help-even-if-i-don-t-know-what-s-wrong', destination: '/blogs/can-counseling-help-even-if-i-don-t-know-what-s-wrong', permanent: true },
      { source: '/how-childhood-trauma-affects-adult-relationships', destination: '/blogs/how-childhood-trauma-affects-adult-relationships', permanent: true },
      { source: '/why-community-support-matters-more-than-ever-in-mental-health', destination: '/blogs/why-community-support-matters-more-than-ever-in-mental-health', permanent: true },
      { source: '/what-happens-when-mental-health-care-is-not-accessible', destination: '/blogs/what-happens-when-mental-health-care-is-not-accessible', permanent: true },
      { source: '/does-seeing-a-counselor-mean-you-re-weak', destination: '/blogs/does-seeing-a-counselor-mean-you-re-weak', permanent: true },
      { source: '/why-talking-to-a-counselor-is-not-weakness', destination: '/blogs/why-talking-to-a-counselor-is-not-weakness', permanent: true },
      { source: '/what-is-trauma-informed-therapy-how-it-helps-in-oklahoma-city-counseling', destination: '/blogs/what-is-trauma-informed-therapy-how-it-helps-in-oklahoma-city-counseling', permanent: true },
      { source: '/how-does-unresolved-trauma-affect-daily-life-signs-when-to-seek-help-in-oklahoma-city', destination: '/blogs/how-does-unresolved-trauma-affect-daily-life-signs-when-to-seek-help-in-oklahoma-city', permanent: true },
      { source: '/how-do-i-know-if-i-need-counseling-or-just-someone-to-talk-to', destination: '/blogs/how-do-i-know-if-i-need-counseling-or-just-someone-to-talk-to', permanent: true },
      { source: '/why-emotional-burnout-is-becoming-the-new-normal', destination: '/blogs/why-emotional-burnout-is-becoming-the-new-normal', permanent: true },
      { source: '/what-happens-when-grief-is-ignored-instead-of-processed', destination: '/blogs/what-happens-when-grief-is-ignored-instead-of-processed', permanent: true },
      { source: '/why-people-minimize-emotional-pain', destination: '/blogs/why-people-minimize-emotional-pain', permanent: true },
      { source: '/why-talking-to-a-counselor-is-not-a-sign-of-weakness', destination: '/blogs/why-talking-to-a-counselor-is-not-a-sign-of-weakness', permanent: true },
      { source: '/how-does-unresolved-trauma-show-up-in-everyday-life', destination: '/blogs/how-does-unresolved-trauma-show-up-in-everyday-life', permanent: true },
      { source: '/grief-counseling-in-okc-5-signs-youre-ready-to-talk-to-a-therapist', destination: '/blogs/grief-counseling-in-okc-5-signs-youre-ready-to-talk-to-a-therapist', permanent: true },
      { source: '/trauma-informed-counseling-in-oklahoma-city-what-it-is-and-how-it-helps-kids-and-families', destination: '/blogs/trauma-informed-counseling-in-oklahoma-city-what-it-is-and-how-it-helps-kids-and-families', permanent: true },
      { source: '/crisis-response-101-handling-mental-health-emergencies', destination: '/blogs/crisis-response-101-handling-mental-health-emergencies', permanent: true },
      { source: '/workplace-mental-health-response-plan-step-by-step-guide', destination: '/blogs/workplace-mental-health-response-plan-step-by-step-guide', permanent: true },
      { source: '/mental-health-first-aid-vs-de-escalation-training-which-does-your-team-need', destination: '/blogs/mental-health-first-aid-vs-de-escalation-training-which-does-your-team-need', permanent: true },
      { source: '/recognizing-burnout-vs-depression-at-work', destination: '/blogs/recognizing-burnout-vs-depression-at-work', permanent: true },
      { source: '/what-is-trauma-bonding-and-how-does-it-affect-your-life', destination: '/blogs/what-is-trauma-bonding-and-how-does-it-affect-your-life', permanent: true },
      { source: '/top-benefits-of-marriage-counseling-in-oklahoma-city', destination: '/blogs/top-benefits-of-marriage-counseling-in-oklahoma-city', permanent: true },
      { source: '/how-oklahoma-city-is-training-for-mental-health-team-resilience', destination: '/blogs/how-oklahoma-city-is-training-for-mental-health-team-resilience', permanent: true },
      { source: '/does-oklahoma-offer-in-home-support-services-a-complete-guide-for-families', destination: '/blogs/does-oklahoma-offer-in-home-support-services-a-complete-guide-for-families', permanent: true },
      { source: '/employee-mental-health-support-how-managers-build-trust', destination: '/blogs/employee-mental-health-support-how-managers-build-trust', permanent: true },
      { source: '/top-6-reasons-people-in-okc-are-choosing-individual-counseling-in-2025', destination: '/blogs/top-6-reasons-people-in-okc-are-choosing-individual-counseling-in-2025', permanent: true },
      { source: '/the-emotional-mental-benefits-of-couple-counseling-for-okc-residents', destination: '/blogs/the-emotional-mental-benefits-of-couple-counseling-for-okc-residents', permanent: true },
      { source: '/4-ways-depression-can-affect-your-relationships', destination: '/blogs/4-ways-depression-can-affect-your-relationships', permanent: true },
      { source: '/best-5-strategies-to-enhance-positive-mental-health-in-workplaces', destination: '/blogs/best-5-strategies-to-enhance-positive-mental-health-in-workplaces', permanent: true },
      { source: '/proven-parent-training-for-happy-families-healthy-relationships', destination: '/blogs/proven-parent-training-for-happy-families-healthy-relationships', permanent: true },
      { source: '/what-does-trauma-informed-communication-look-like', destination: '/blogs/what-does-trauma-informed-communication-look-like', permanent: true },
      { source: '/mental-health-challenges-in-oklahoma-breaking-the-stigma-and-finding-support', destination: '/blogs/mental-health-challenges-in-oklahoma-breaking-the-stigma-and-finding-support', permanent: true },
      { source: '/the-impact-of-community-support-on-foster-care-in-oklahoma', destination: '/blogs/the-impact-of-community-support-on-foster-care-in-oklahoma', permanent: true },
      { source: '/how-community-support-shapes-the-future', destination: '/blogs/how-community-support-shapes-the-future', permanent: true },
      { source: '/mental-health', destination: '/blogs/mental-health', permanent: true },
      { source: '/how-to-build-emotional-intelligence-in-children', destination: '/blogs/how-to-build-emotional-intelligence-in-children', permanent: true },
    ];
  },
};

export default nextConfig;
