import Link from 'next/link';
import ScrollReveal from '@/components/ScrollReveal';

export const metadata = { title: 'Depression Counseling Oklahoma | Open Arms Initiative', description: 'Find compassionate depression counseling in Oklahoma. Open Arms Initiative provides support for depression, anxiety, stress, and emotional well-being.', alternates: { canonical: 'https://www.openarmsinitiative.com/depression-anxiety-counseling-oklahoma/' } };

const trustIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20.5s-6.5-4-9-8.2C1.2 8.8 3 5.5 6.2 5.5c1.9 0 3.2 1 3.8 2.1.6-1.1 1.9-2.1 3.8-2.1 3.2 0 5 3.3 3.2 6.8-2.5 4.2-9 8.2-9 8.2Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3.5 19 6v6c0 4.5-3 7.5-7 8.5-4-1-7-4-7-8.5V6l7-2.5Z" /><path d="m9.3 12 1.9 1.9 3.6-3.9" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8.5" r="3.3" /><path d="M5.5 20c.8-4 3-6.2 6.5-6.2s5.7 2.2 6.5 6.2" /><path d="M12 5.2v6.6M9 8.5h6" strokeDasharray="1.6 2.2" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><rect x="3.5" y="4.5" width="17" height="16" rx="2.2" /><path d="M3.5 9.5h17" /><path d="M8 3v3M16 3v3" /><path d="m8.3 14.3 2 2 4.3-4.3" /></svg>,
];

const feelingIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M9 18.5h6M10 21h4" /><path d="M12 3a6.5 6.5 0 0 0-3.8 11.8c.5.4.8 1 .8 1.7v.5h6v-.5c0-.7.3-1.3.8-1.7A6.5 6.5 0 0 0 12 3Z" /><path d="M9 8.5c1-1.3 2-2 3-2s2 .7 3 2" strokeDasharray="1.3 2" /><path d="M12 9.5v3.2" strokeDasharray="1.1 1.6" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="2.5" y="8" width="16" height="8" rx="2" /><path d="M20.5 10.5v3" /><path d="M5.5 11v2" strokeDasharray="1 1.4" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 13.5A7.5 7.5 0 1 1 12 21" /><path d="M4.5 13.5 2.7 12M4.5 13.5l1.6-2" /><path d="M9.5 11.3a2.6 2.6 0 1 1 2.6 2.6" strokeDasharray="1.3 2" /><circle cx="12" cy="16.3" r=".3" fill="currentColor" stroke="none" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20.5s-6.5-4-9-8.2C1.2 8.8 3 5.5 6.2 5.5c1.9 0 3.2 1 3.8 2.1.6-1.1 1.9-2.1 3.8-2.1 3.2 0 5 3.3 3.2 6.8-2.5 4.2-9 8.2-9 8.2Z" /><path d="m4 4 16 16" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M2.5 13h4l1.8-4.5L11 17.5l2-9 1.6 4.5h4.9" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="7" cy="8" r="3" /><path d="M2 19c.5-3.3 2.2-5.2 5-5.2" strokeDasharray="1.3 2" /><path d="M14 4.5a3 3 0 0 1 0 5.8" strokeDasharray="1.3 2" /><path d="M22 19c-.4-2.6-1.6-4.3-3.5-5" strokeDasharray="1.3 2" /></svg>,
];

const feelings = [['Constant Worry','Your mind may feel like it never truly switches off. Thoughts about work, relationships, health, responsibilities, or the future can become difficult to quiet.'],['Feeling Drained','Depression can affect motivation and energy, making everyday responsibilities feel much more difficult than they once did.'],['Overthinking','You may replay conversations, question decisions, or spend significant time worrying about things that haven’t happened.'],['Loss of Interest','Activities, relationships, or experiences that once felt meaningful may no longer bring the same sense of enjoyment or connection.'],['Stress & Overwhelm','When pressure continues without enough opportunity to recover, stress can begin affecting your emotions, relationships, concentration, and everyday functioning.'],['Feeling Disconnected','Sometimes emotional struggles don’t feel like sadness or worry. They can feel like numbness, isolation, or simply not feeling like yourself.']];
const supportIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5c0 4.7-4 8.5-9 8.5a9.5 9.5 0 0 1-3.2-.55L4 21l1.4-3.9A8.4 8.4 0 0 1 3 11.5C3 6.8 7 3 12 3s9 3.8 9 8.5Z" /><path d="m8.5 11.7 2.2 2.2 4.8-4.8" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9" /><path d="M12 7.5v5l3.2 1.9" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12h4l2.2-6.5L13 17.5 15 12h6" /></svg>,
];

const stepIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 4.5h3.2l1.6 4-2 1.6a11 11 0 0 0 5.6 5.6l1.6-2 4 1.6v3.2a1.6 1.6 0 0 1-1.7 1.6A15.5 15.5 0 0 1 3 6.2a1.6 1.6 0 0 1 1.5-1.7Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12a8 8 0 1 1 3 6.2L4 19l.9-3A7.9 7.9 0 0 1 4 12Z" /><path d="M8.5 10.5h7M8.5 14h4.5" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="10.5" cy="10.5" r="6.5" /><path d="m20 20-4.3-4.3" /><path d="M10.5 7.5v6M7.5 10.5h6" strokeDasharray="1.6 2.4" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12h15.5" /><path d="m13.5 6 6 6-6 6" /></svg>,
];

const faqs = [['How do I know if I should seek counseling for depression?', 'Consider speaking with a mental health professional if persistent sadness, low motivation, loss of interest, emotional exhaustion, or other changes are interfering with your relationships, responsibilities, or everyday life. You don’t need to wait until things become unbearable before seeking support.'],['Can counseling help with anxiety and overthinking?', 'Therapy can help you better understand patterns of worry and overthinking, recognize potential triggers, and develop strategies for responding to anxious thoughts and emotions in healthier ways.'],['Can I experience anxiety and depression at the same time?', 'Yes. Anxiety and depression can occur together. Because everyone’s experience is different, a mental health professional can help you explore what you’re experiencing and determine an appropriate approach to care.'],['What happens during anxiety therapy?', 'Your therapist will work to understand your experiences, concerns, triggers, thought patterns, and goals. Counseling may involve exploring patterns contributing to anxiety and developing practical strategies for managing worry, stress, and difficult emotions.'],['Do you provide depression counseling in Oklahoma?', <>Yes. Open Arms Initiative provides <strong>Depression Counseling in Oklahoma</strong> for individuals seeking professional support with emotional difficulties, low mood, stress, and related concerns.</>],['When should I consider counseling for stress?', 'You may consider counseling when stress feels persistent, difficult to manage, or begins affecting your mood, sleep, concentration, relationships, responsibilities, or overall quality of life.']];
export default function DepressionAnxietyPage(){return <main className="da-page">
<ScrollReveal />
<section className="da-hero-outer"><div className="da-hero-bg"><img src="/dep.png" alt="Woman finding support during a depression and anxiety counseling session"/><div className="da-hero-content"><p className="da-kicker">YOU DON’T HAVE TO CARRY THIS ALONE.</p><h1>Depression &amp; Anxiety<br/>Counseling in<br className="da-okc-break"/> Oklahoma</h1><i/><p className="da-lead">When Your Mind Won’t Slow Down, or Life Feels Too Heavy</p><p>Some days, anxiety can make it difficult to quiet your thoughts. Other days, depression can make even ordinary things feel exhausting.</p><p>And sometimes, you experience both, the constant worry of anxiety alongside the heaviness, exhaustion, or disconnection that can come with depression.</p><p>At Open Arms Initiative, we provide compassionate <strong>Depression Counseling in Oklahoma</strong> and anxiety support to help you better understand what you&apos;re experiencing, develop healthier ways to cope, and move forward with professional support.</p><div className="da-actions"><Link href="/contact" className="da-btn da-solid">Request an Appointment</Link><a href="#approach" className="da-btn da-outline">Explore Our Approach</a></div></div></div></section>
<section className="da-trust-section"><div className="da-container da-trust reveal reveal-from-bottom">{['Compassionate Care','Confidential Support','Personalized Therapy','In-Person & Online'].map((x,i)=><div key={x}><span>{trustIcons[i]}</span>{x}</div>)}</div></section>
<section className="da-section da-heavy"><div className="da-container"><h2>When Everything Feels Like More Than It Should</h2><p>You may be getting through your days while quietly struggling inside. Maybe your mind keeps replaying conversations and imagining everything that could go wrong. Maybe getting out of bed takes more energy than anyone realizes. Maybe you&apos;re irritable with people you love, withdrawing from things you once enjoyed, or constantly telling yourself: <strong>“I should be able to handle this.”</strong></p><p>You don&apos;t need to compare your struggles to anyone else&apos;s before deciding they matter. <strong>If life has become harder to carry, you deserve a place to talk about it.</strong></p></div></section>
<section className="da-section da-feelings"><div className="da-container reveal reveal-from-left"><aside><h2>What Have Your Days Been<br/>Feeling <em>Like?</em></h2><i className="da-feelings-line" /><p>You are not alone in what you’re going through. And you don’t have to figure it out alone.</p></aside><div>{feelings.map(([h,p],i)=><article key={h}><span>{feelingIcons[i]}</span><h3>{h}</h3><i /><p>{p}</p></article>)}</div></div></section>
<section id="approach" className="da-section"><div className="da-container"><div className="da-more"><img src="/mg9.jpg" alt="Support group having an open conversation together"/><div><p className="da-kicker">ANXIETY THERAPY OKC</p><h2>You Are More Than What You’re Feeling Right Now</h2><p>When depression or anxiety has been present for a while, it can begin to shape the way you see yourself and your future. Therapy creates space to look at what you&apos;re experiencing with support rather than judgment.</p><p>Through <strong>Anxiety Therapy in OKC</strong> and depression counseling, your therapist can help you explore your experiences, recognize patterns, develop coping strategies, and work toward goals that matter to you.</p><p>Counseling may help you work on:</p><ul>{['Understanding emotional patterns and triggers','Managing persistent worry','Developing healthier coping strategies','Responding differently to overwhelming thoughts','Managing stress more effectively','Improving communication and boundaries','Reconnecting with meaningful activities','Developing greater self-awareness','Building routines that support emotional well-being'].map(x=><li key={x}>{x}</li>)}</ul><p><strong>You don&apos;t have to solve everything at once. Progress can begin with one manageable step.</strong></p></div></div></div></section>
<section className="da-statement"><div className="da-container reveal reveal-scale-in"><div><h2>“You’ve been surviving the days. Therapy can give you space to start experiencing them differently.”</h2><Link href="/contact" className="da-btn da-light">Request a Counseling Appointment</Link></div><img src="/black-white-analog-portrait-woman-posing-indoors-100kb.jpg" alt="Woman pausing quietly, eyes closed, in soft window light"/><aside>You don&apos;t have to pretend you&apos;re okay in the counseling room.<br/><br/>You can arrive tired.<br/>You can arrive uncertain.<br/>You can arrive without knowing exactly what to say.<br/><br/>We&apos;ll start where you are.</aside></div></section>
<section className="da-section da-support-section"><div className="da-container da-support"><div className="reveal reveal-from-left"><h2>Support That Meets You Where You Are</h2>{[['A Place to Be Honest','You don’t need to minimize what you’re experiencing or worry about being a burden. Counseling provides confidential space to talk openly about what has been difficult.'],['Understanding What’s Happening','Your therapist works with you to explore thoughts, emotions, experiences, stressors, and patterns that may be affecting your well-being.'],['Practical Ways Forward','Understanding is important, but so are tools you can use outside therapy. Counseling can help you develop strategies for managing stress, responding to difficult thoughts and emotions, and navigating everyday challenges.']].map(([h,p],i)=><article key={h}><span>{supportIcons[i]}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div><div className="da-stress reveal reveal-from-right"><h2>When Stress Starts Following You Everywhere</h2><p>Stress is part of life, but ongoing stress can become difficult to manage when there is little opportunity to recover.</p><ul className="da-stress-list">{['Work.','Finances.','Relationships.','Parenting.','Caregiving.','Major changes.'].map(x=><li key={x}>{x}</li>)}</ul><p>Sometimes it isn&apos;t one enormous problem, it is <strong>everything happening at the same time.</strong></p><p>Our <strong>Stress Management Counseling in Oklahoma</strong> provides space to identify sources of stress, understand how they affect you, and develop healthier ways to respond.</p><p>You may not be able to remove every stressful situation from your life. But you can learn different ways to navigate them.</p></div></div></section>
<section className="da-section da-steps-section"><div className="da-container reveal reveal-from-right"><h2 className="da-center">What to Expect</h2><div className="da-steps">{[['Connect','Reach out to Open Arms Initiative to request an appointment.'],['Be Heard','Your therapist takes time to understand what you’ve been experiencing and how it has been affecting your everyday life.'],['Understand','Together, you’ll explore relevant patterns, stressors, concerns, and goals for counseling.'],['Move Forward','You’ll work on strategies and skills that can support healthier ways of navigating your thoughts, emotions, stress, and everyday experiences.']].map(([h,p],i)=><article key={h}><span>{stepIcons[i]}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
<section className="da-section"><div className="da-container"><div className="da-faq"><aside><h2>It&apos;s okay to have questions before asking for help.</h2><p>We&apos;re here to provide answers, guidance, and support so you can take the next step with confidence.</p></aside><div><h2>Questions About Depression &amp; Anxiety Counseling</h2>{faqs.map(([q,a])=><details key={q} name="da-faq-group"><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></div></section>
<section className="da-final"><div className="da-container"><div className="da-final-photo"><img src="/new1.jpg" alt="Cup by a window"/></div><div><h2>You Don’t Need to Feel Better Before You Ask for Help.</h2><p>When you&apos;re struggling, even reaching out can feel like another difficult thing to do. So don&apos;t think about solving everything today. Think about taking <strong>one step.</strong> One conversation. One place where you don&apos;t have to pretend.</p><h3>There Can Be More Ahead Than What You’re Feeling Right Now.</h3></div><Link href="/contact" className="da-btn da-solid">Request an Appointment</Link></div></section>
</main>}
