import Link from 'next/link';
import ScrollReveal from '@/components/ScrollReveal';

export const metadata = { title: 'Child Counseling Services Oklahoma City | Open Arms', description: 'Compassionate child counseling services in Oklahoma City for children and teens facing emotional, behavioral, family, school, and life challenges.', alternates: { canonical: 'https://www.openarmsinitiative.com/child-counseling-oklahoma-city/' } };

const SCHEMA_BREADCRUMB = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.openarmsinitiative.com/' },
    { '@type': 'ListItem', position: 2, name: 'Child & Adolescent Counseling', item: 'https://www.openarmsinitiative.com/child-counseling-oklahoma-city/' },
  ],
};

const SCHEMA_SERVICE = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  serviceType: 'Child Counseling',
  provider: {
    '@type': 'Organization',
    name: 'Open Arms Initiative',
    url: 'https://www.openarmsinitiative.com/',
  },
  areaServed: 'Oklahoma City, OK',
  description: 'Compassionate child counseling services in Oklahoma City for children and teens facing emotional, behavioral, family, school, and life challenges.',
};

const SCHEMA_FAQ = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    { '@type': 'Question', name: 'How do I know if my child may benefit from counseling?', acceptedAnswer: { '@type': 'Answer', text: 'Consider speaking with a mental health professional if you’ve noticed persistent changes in your child’s mood, behavior, relationships, school experience, communication, or ability to cope with everyday challenges. You can also seek counseling simply because your child is navigating a difficult transition and could benefit from additional support.' } },
    { '@type': 'Question', name: 'What happens during child counseling?', acceptedAnswer: { '@type': 'Answer', text: 'The counseling process depends on your child’s age, needs, concerns, and treatment goals. A therapist may use developmentally appropriate conversations, activities, and therapeutic approaches to help your child communicate, explore emotions, and develop healthy coping skills.' } },
    { '@type': 'Question', name: 'What if my child doesn’t want to talk?', acceptedAnswer: { '@type': 'Answer', text: 'Children and teenagers may need time before they feel comfortable opening up. Therapists work to establish trust and create an environment where young people can engage at an appropriate pace rather than expecting them to immediately discuss difficult experiences.' } },
    { '@type': 'Question', name: 'Are parents involved in child counseling?', acceptedAnswer: { '@type': 'Answer', text: 'Parent or caregiver involvement can vary based on the child’s age, needs, treatment goals, and confidentiality considerations. Your therapist can explain how you may participate and how you can support your child’s progress outside therapy.' } },
    { '@type': 'Question', name: 'Do you provide counseling for teenagers in Oklahoma City?', acceptedAnswer: { '@type': 'Answer', text: 'Open Arms Initiative provides counseling support for children and adolescents in Oklahoma City. Therapy can address age-appropriate emotional, relational, family, school, and life-transition concerns based on the young person’s individual needs.' } },
    { '@type': 'Question', name: 'Can counseling help when our whole family is struggling?', acceptedAnswer: { '@type': 'Answer', text: 'When concerns involve broader family relationships or communication patterns, Family Counseling may also be appropriate. Your provider can help determine which counseling approach best fits your family’s needs.' } },
  ],
};

const trustIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20.5s-6.5-4-9-8.2C1.2 8.8 3 5.5 6.2 5.5c1.9 0 3.2 1 3.8 2.1.6-1.1 1.9-2.1 3.8-2.1 3.2 0 5 3.3 3.2 6.8-2.5 4.2-9 8.2-9 8.2Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="3.2" /><path d="M5.5 20c.8-4.2 3.1-6.4 6.5-6.4s5.7 2.2 6.5 6.4" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4 21c0-4.4 2.4-6.7 5.2-7.3M20 21c0-4.4-2.4-6.7-5.2-7.3" /><circle cx="9.2" cy="8" r="3" /><circle cx="14.8" cy="8" r="3" strokeDasharray="1.3 2" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3.5 19 6v6c0 4.5-3 7.5-7 8.5-4-1-7-4-7-8.5V6l7-2.5Z" /><path d="m9.3 12 1.9 1.9 3.6-3.9" /></svg>,
];

const feelingIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20.5s-6.5-4-9-8.2C1.2 8.8 3 5.5 6.2 5.5c1.9 0 3.2 1 3.8 2.1.6-1.1 1.9-2.1 3.8-2.1 3.2 0 5 3.3 3.2 6.8-2.5 4.2-9 8.2-9 8.2Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 13.5A7.5 7.5 0 1 1 12 21" /><path d="M4.5 13.5 2.7 12M4.5 13.5l1.6-2" /><path d="M9.5 11.3a2.6 2.6 0 1 1 2.6 2.6" strokeDasharray="1.3 2" /><circle cx="12" cy="16.3" r=".3" fill="currentColor" stroke="none" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="3.5" y="4.5" width="17" height="16" rx="2.2" /><path d="M3.5 9.5h17" /><path d="M8 3v3M16 3v3" /><path d="m8.3 14.3 2 2 4.3-4.3" strokeDasharray="1.3 2" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="7.5" r="3" /><path d="M2.8 19.5c.6-3.8 2.8-5.8 6.2-5.8s5.6 2 6.2 5.8" /><path d="M16 4.3c1.3.3 2.3 1.5 2.3 3s-1 2.7-2.3 3" strokeDasharray="1.4 1.8" /><path d="M17 14c2 .4 3.4 2 3.9 4.8" strokeDasharray="1.4 1.8" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M4 21c0-4.4 2.4-6.7 5.2-7.3M20 21c0-4.4-2.4-6.7-5.2-7.3" /><circle cx="9.2" cy="8" r="3" /><circle cx="14.8" cy="8" r="3" strokeDasharray="1.3 2" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3.2s5.5 6.7 5.5 11a5.5 5.5 0 0 1-11 0c0-4.3 5.5-11 5.5-11Z" /><path d="M9.3 15.2a2.7 2.7 0 0 0 2.7 2.7" strokeDasharray="1.3 1.8" /></svg>,
];

const feelings = [
  ['Big Emotions', 'Some children experience emotions that feel bigger than their ability to understand or communicate them. Counseling can help them recognize feelings and develop healthier ways to express them.'],
  ['Changes in Behavior', 'Increased irritability, withdrawal, emotional outbursts, or noticeable changes in behavior may be ways a child communicates that something feels difficult.'],
  ['School Challenges', 'Academic pressure, changing routines, social difficulties, bullying, or problems adjusting at school can affect a child’s emotional well-being.'],
  ['Friendship & Social Concerns', 'Friendships can become an important source of belonging—and stress—as children grow. Counseling can provide space to explore social challenges and healthy relationships.'],
  ['Family Changes', 'Divorce, separation, blended families, relocation, loss, foster care, adoption, or other changes at home can bring emotions children may struggle to understand.'],
  ['Growing Up', 'Adolescence can bring changing identities, responsibilities, relationships, expectations, and emotions. Having a trusted space outside the immediate family can help teens process those experiences.'],
];

const supportIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M21 11.5c0 4.7-4 8.5-9 8.5a9.5 9.5 0 0 1-3.2-.55L4 21l1.4-3.9A8.4 8.4 0 0 1 3 11.5C3 6.8 7 3 12 3s9 3.8 9 8.5Z" /><path d="m8.5 11.7 2.2 2.2 4.8-4.8" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><circle cx="8.5" cy="8" r="3" /><path d="M2.5 19.2c.6-3.4 2.7-5.1 6-5.1s5.4 1.7 6 5.1" /><path d="M16 4.6c1.3.3 2.2 1.4 2.2 2.9s-.9 2.6-2.2 2.9" strokeDasharray="1.3 1.7" /><path d="M17 14.2c1.9.5 3.1 1.9 3.5 4.6" strokeDasharray="1.3 1.7" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4 21c0-4.4 2.4-6.7 5.2-7.3M20 21c0-4.4-2.4-6.7-5.2-7.3" /><circle cx="9.2" cy="8" r="3" /><circle cx="14.8" cy="8" r="3" strokeDasharray="1.3 2" /></svg>,
];

const stepIcons = [
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 4.5h3.2l1.6 4-2 1.6a11 11 0 0 0 5.6 5.6l1.6-2 4 1.6v3.2a1.6 1.6 0 0 1-1.7 1.6A15.5 15.5 0 0 1 3 6.2a1.6 1.6 0 0 1 1.5-1.7Z" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M4 12a8 8 0 1 1 3 6.2L4 19l.9-3A7.9 7.9 0 0 1 4 12Z" /><path d="M8.5 10.5h7M8.5 14h4.5" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><rect x="3.5" y="4.5" width="17" height="16" rx="2.2" /><path d="M3.5 9.5h17" /><path d="m8.3 14.3 2 2 4.3-4.3" strokeDasharray="1.3 2" /></svg>,
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12h15.5" /><path d="m13.5 6 6 6-6 6" /></svg>,
];

const faqs = [
  ['How do I know if my child may benefit from counseling?', 'Consider speaking with a mental health professional if you’ve noticed persistent changes in your child’s mood, behavior, relationships, school experience, communication, or ability to cope with everyday challenges. You can also seek counseling simply because your child is navigating a difficult transition and could benefit from additional support.'],
  ['What happens during child counseling?', 'The counseling process depends on your child’s age, needs, concerns, and treatment goals. A therapist may use developmentally appropriate conversations, activities, and therapeutic approaches to help your child communicate, explore emotions, and develop healthy coping skills.'],
  ['What if my child doesn’t want to talk?', 'Children and teenagers may need time before they feel comfortable opening up. Therapists work to establish trust and create an environment where young people can engage at an appropriate pace rather than expecting them to immediately discuss difficult experiences.'],
  ['Are parents involved in child counseling?', 'Parent or caregiver involvement can vary based on the child’s age, needs, treatment goals, and confidentiality considerations. Your therapist can explain how you may participate and how you can support your child’s progress outside therapy.'],
  ['Do you provide counseling for teenagers in Oklahoma City?', <>Open Arms Initiative provides counseling support for children and adolescents in Oklahoma City. Therapy can address age-appropriate emotional, relational, family, school, and life-transition concerns based on the young person&rsquo;s individual needs.</>],
  ['Can counseling help when our whole family is struggling?', <>When concerns involve broader family relationships or communication patterns, <Link href="/family-therapy-oklahoma-city/">Family Counseling</Link> may also be appropriate. Your provider can help determine which counseling approach best fits your family&rsquo;s needs.</>],
];

export default function ChildCounselingPage() { return <main className="ca-page">
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_BREADCRUMB) }} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_SERVICE) }} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_FAQ) }} />
  <ScrollReveal />
  <section className="ca-hero-outer"><div className="ca-hero-bg"><img src="/ch.png" alt="Child feeling supported during a counseling session in Oklahoma City" /><div className="ca-container ca-hero-content"><p className="ca-kicker">HELPING YOUNG HEARTS FEEL HEARD.</p><h1>Child Counseling Services<br />in Oklahoma City</h1><i /><p className="ca-lead">When Your Child Is Struggling, You Don&rsquo;t Have to Find the Answers Alone</p><p>You know your child. You notice when their smile changes, when they become quieter than usual, when frustration turns into frequent outbursts, or when school and friendships start to feel harder.</p><p>Sometimes children and teens don&apos;t have the words to explain what they&apos;re feeling. At Open Arms Initiative, our <strong>Child Counseling Services in Oklahoma City</strong> provide a supportive environment where children and adolescents can express themselves, feel understood, develop healthy coping skills, and receive professional support through life&apos;s challenges.</p><div className="ca-actions"><Link href="/contact" className="ca-btn ca-solid">Request an Appointment</Link><a href="#approach" className="ca-btn ca-outline">Explore Child &amp; Teen Counseling</a></div></div></div></section>
  <section className="ca-trust-section"><div className="ca-container ca-trust">{['Compassionate Care', 'Child & Teen Focused', 'Family-Supportive', 'Safe & Confidential'].map((x, i) => <div key={x}><span>{trustIcons[i]}</span><p>{x}</p></div>)}</div></section>
  <section className="ca-section ca-heavy"><div className="ca-container reveal reveal-from-bottom"><h2>You Know Your Child: Trust Yourself When Something Feels Different</h2><p>Maybe you&apos;ve asked, &ldquo;What&apos;s wrong?&rdquo; And they answered, &ldquo;Nothing.&rdquo; But you can tell something is there.</p><p>Children and teenagers don&apos;t always experience or communicate emotions the way adults do. Sometimes difficult feelings appear through behavior, withdrawal, irritability, changes at school, trouble communicating, or shifts in relationships.</p><p><strong>Seeking counseling doesn&apos;t mean you&apos;ve failed as a parent. It means you&apos;re paying attention.</strong> And reaching out for support can give your child another safe person to help them understand what they&apos;re experiencing.</p></div></section>
  <section className="ca-section ca-feelings"><div className="ca-container"><div className="ca-feelings-head reveal reveal-from-bottom"><h2>What Might Your Child<br />Be Going <em>Through?</em></h2><i className="ca-feelings-line" /></div><div className="ca-feel-timeline reveal-stagger">{feelings.map(([h, p], i) => <div className="reveal reveal-from-bottom ca-feel-item" key={h}><span className="ca-feel-node">{feelingIcons[i]}</span><div className="ca-feel-copy"><h3>{h}</h3><p>{p}</p></div></div>)}</div></div></section>
  <section id="approach" className="ca-section"><div className="ca-container"><div className="ca-more"><div className="ca-more-media reveal reveal-from-left"><img src="/chx.jpg" alt="Therapist listening attentively to a child during a counseling session" /></div><div className="reveal reveal-from-right"><p className="ca-kicker-label">SOMETIMES BEHAVIOR IS COMMUNICATION</p><h2>Behind the Behavior Is a Young Person Trying to Make Sense of What They Feel</h2><p>A child may not say, &ldquo;I&apos;m overwhelmed.&rdquo; They might become angry. They may not say, &ldquo;I&apos;m worried about what is happening at home.&rdquo; They might become quieter. A teenager may not say, &ldquo;I don&apos;t know who I can talk to.&rdquo; They may begin pulling away.</p><p>Behavior doesn&apos;t always tell us exactly what is happening, but it can tell us that something deserves attention. Counseling gives children and adolescents an age-appropriate environment to explore emotions, experiences, relationships, and concerns with professional support.</p><p><strong>Behind the behavior is a young person trying to make sense of what they feel.</strong></p></div></div></div></section>
  <section className="ca-statement"><div className="ca-container reveal reveal-scale-in"><div><h2>&ldquo;Your child doesn&rsquo;t need to have the right words. They need to know there is a safe place to find them.&rdquo;</h2><Link href="/contact" className="ca-btn ca-light">Request a Child Counseling Appointment</Link></div><img src="/ch7.jpg" alt="Parent and child sharing a calm, supportive moment together" /><aside>You don&apos;t have to know exactly what&apos;s happening before reaching out.<br /><br />And your child doesn&apos;t need to arrive ready to explain everything.<br /><br />We can start by creating a space where they feel safe enough to simply be themselves.</aside></div></section>
  <section className="ca-section ca-safe-section"><div className="ca-container"><h2 className="ca-center reveal reveal-from-bottom">A Space Designed to Help Children &amp; Teens Feel Safe</h2><i className="ca-line-center" /><div className="ca-safe reveal-stagger">{[['For Younger Children', 'Children may communicate differently from adults. Depending on the child’s needs and the clinician’s approach, counseling may use age-appropriate conversation, activities, and other methods to help children communicate and explore emotions.'], ['For Adolescents', 'Teenagers may need a place where they can speak honestly about emotions, relationships, school, family, identity, expectations, or other concerns without feeling judged.'], ['For Parents & Caregivers', 'Supporting the child can also involve supporting the adults who care for them. When appropriate, therapists can work with parents or caregivers to help them better understand concerns, reinforce healthy strategies, and support progress outside counseling.']].map(([h, p]) => <article className="reveal reveal-from-bottom" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="ca-section ca-support-section ca-support-section-a"><div className="ca-container"><div className="ca-support-block reveal reveal-from-bottom"><h2>Helping Your Child Build Skills They Can Carry Forward</h2><p>Counseling isn&apos;t about changing who your child is. It&apos;s about helping them better understand themselves and develop skills for navigating difficult experiences.</p><p>Depending on your child&apos;s individual needs and goals, counseling may support:</p><ul>{['Recognizing and expressing emotions', 'Developing healthy coping strategies', 'Improving communication', 'Building confidence and self-awareness', 'Navigating friendships and relationships', 'Adjusting to family or life changes', 'Developing problem-solving skills', 'Managing difficult feelings', 'Strengthening family communication', 'Building emotional resilience'].map(x => <li key={x}>{x}</li>)}</ul><p><strong>The goal is not a child who never struggles. It&apos;s helping your child develop healthier ways to understand and navigate those struggles.</strong></p></div></div></section>
  <section className="ca-section ca-support-section ca-support-section-b"><div className="ca-container"><div className="ca-support-block reveal reveal-from-bottom"><h2>You&rsquo;re Part of Their Support System</h2><p>Parents sometimes wonder: &ldquo;Will I be involved in my child&apos;s counseling?&rdquo;</p><p>The answer depends on factors such as your child&apos;s age, needs, treatment goals, and appropriate confidentiality considerations. Parents and caregivers can be important partners in supporting a child&apos;s emotional well-being.</p><p>Your therapist can explain what involvement may look like, what information can appropriately be shared, and how you can support your child outside sessions.</p><p>When the whole family is experiencing broader challenges, families may also benefit from our <Link href="/family-therapy-oklahoma-city/">Family Counseling</Link> services.</p></div></div></section>
  <section className="ca-section ca-steps-section"><div className="ca-container"><h2 className="ca-center reveal reveal-from-bottom">What to Expect</h2><i className="ca-line-center" /><div className="ca-steps reveal-stagger">{[['Connect', 'Reach out to Open Arms Initiative to discuss counseling and request an appointment.'], ['Understand', 'Your therapist works to learn more about your child’s experiences, concerns, strengths, and needs.'], ['Create a Supportive Plan', 'Counseling is tailored to your child’s age, circumstances, and therapeutic goals.'], ['Grow', 'Over time, counseling can help your child develop greater emotional awareness, communication skills, coping strategies, and confidence in navigating challenges.']].map(([h, p], i) => <article className="reveal reveal-from-bottom" key={h}><span className="ca-step-icon">{stepIcons[i]}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="ca-section"><div className="ca-container"><div className="ca-faq"><aside className="reveal reveal-from-left"><h2>Questions Parents Often Ask</h2><p>Find answers to common questions about child and adolescent counseling and what to expect.</p></aside><div className="reveal reveal-from-right">{faqs.map(([q, a]) => <details key={q} name="ca-faq-group"><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></div></section>
  <section className="ca-final"><div className="ca-container ca-final-grid reveal reveal-scale-in"><div><h2>You Don&rsquo;t Need to Have Every Answer to Help Your Child Take the Next Step</h2><p>You noticed something. You care. And you&apos;re looking for a way to help. That already matters.</p><h3>Give Them a Safe Place to Be Heard, Understood, and Supported.</h3><p>Open Arms Initiative is here to support your child, and help you feel less alone in figuring out what comes next.</p></div><Link href="/contact" className="ca-btn ca-solid">Request an Appointment</Link></div></section>
</main>}
