import Link from 'next/link';

export const metadata = { title: 'Grief Counseling Oklahoma City | Open Arms Initiative', description: 'Find compassionate grief counseling in Oklahoma City. Open Arms Initiative provides supportive therapy for bereavement, loss, life changes, and healing.' };

const feelings=[['◌','Deep Sadness','Waves of sadness may arrive unexpectedly, even long after the loss occurred.'],['♧','Numbness & Disconnection','Grief can sometimes feel like being distant from yourself or everyday life.'],['ϟ','Anger & Frustration','You may feel angry about what happened or the unfairness of it all.'],['◉','Guilt & “What If” Thoughts','You may replay moments and wonder whether something could have happened differently.'],['〰','Difficulty Adjusting','Loss can change routines, relationships, and plans for the future.'],['♡','Feeling Alone in Your Grief','It can feel like no one truly understands what you’re carrying.']];
const losses=[['♙','Death of Someone you Love','The death of a family member, partner, friend, or another important person can change everyday life.'],['♡','Relationship Loss','Divorce, separation, estrangement, and endings can involve genuine grief.'],['◒','Pregnancy or Infant Loss','Deeply personal grief that others may not always know how to acknowledge.'],['⌂','Major Life Changes','Retirement, relocation, caregiving, or losing an important role.'],['☼','Loss of a Future you Expected','Grief can come from losing plans, possibilities, or a future imagined.']];
const faqs=[['How do I know if I need grief counseling?','There is no specific level of grief you must reach. Consider support if your loss feels difficult to process, affects responsibilities or relationships, or you want a private place to talk.'],['Is grief counseling only for someone who has experienced a death?','No. Grief can follow relationship endings, pregnancy loss, estrangement, major life changes, or the loss of an expected future.'],['How long does grief last?','There is no universal timeline. Grief changes over time, and counseling supports your individual experience rather than a schedule.'],['What happens during grief counseling?','You have space to talk about your loss and explore the emotions, memories, changes, and concerns connected with it.'],['Do you provide grief counseling in Oklahoma City?','Yes. Open Arms Initiative provides compassionate, professional support for bereavement, significant loss, and major life changes.'],['Can I attend grief counseling individually?','Yes. Individual counseling provides private, one-on-one support tailored to your experience and needs.']];

export default function GriefPage(){return <main className="grief-page">
<section className="grief-hero"><div className="grief-wrap grief-hero-grid"><div><p className="grief-kicker">YOU DON’T HAVE TO GRIEVE ALONE.</p><h1>Grief Counseling<br/><i>in Oklahoma City</i></h1><h2>There Is No Right Way—or Right Timeline—to Grieve</h2><p>Loss can change the way everything feels. The world keeps moving, but part of you may feel like it has stopped. Some days bring sadness. Others bring anger, confusion, guilt, numbness—or emotions you weren't expecting.</p><p>At Open Arms Initiative, our Grief Counseling in Oklahoma City provides a compassionate space to process loss, understand what you’re experiencing, and find support as you learn to carry what has changed.</p><div className="grief-actions"><Link href="/contact" className="grief-btn">Request an Appointment　⌁</Link><a href="#support" className="grief-btn outline">Explore Grief Support</a></div><div className="grief-trust">{['♧ Compassionate Support','♙ Safe & Confidential','◯ Personalized Care','▱ In-Person & Online'].map(x=><span key={x}>{x}</span>)}</div></div><div className="grief-visual"><div className="grief-window"><span>it’s okay<br/>to take<br/>the time<br/>you need.</span><div className="grief-cup">◒</div></div><div className="grief-leaf">❧</div></div></div></section>
<section className="grief-feelings"><div className="grief-wrap feelings-grid"><aside><h2>What Can<br/><i>Grief Feel Like?</i></h2><p>Grief can show up in many ways. There is no one way you’re “supposed” to feel.</p></aside><div className="feelings-cards">{feelings.map(([icon,h,p])=><article key={h}><b>{icon}</b><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
<section className="grief-forward"><div className="grief-wrap forward-grid"><div className="quote"><span>“</span><h2>You don’t have to stop missing them to begin caring for yourself again.</h2></div><div><h2>You Don’t Have to “Move On” to Move Forward</h2><p>Grief counseling isn’t about forgetting or forcing yourself to stop feeling sad. Through Bereavement Therapy in OKC, you can talk about what you lost and how it has affected your life.</p><ul>{['Process difficult emotions','Adjust to changes after a loss','Explore guilt, anger, or confusion','Develop ways to cope','Navigate relationship changes','Find ways to honor memories','Reconnect at your own pace','Discover what moving forward means for you'].map(x=><li key={x}>♡ {x}</li>)}</ul></div></div></section>
<section id="support" className="grief-losses"><div className="grief-wrap"><h2 className="center">Support for Different Kinds of Loss</h2><p className="center intro">Our Loss Support Counseling in Oklahoma City provides compassionate space for many forms of loss.</p><div className="loss-grid">{losses.map(([i,h,p])=><article key={h}><b>{i}</b><h3>{h}</h3><p>{p}</p></article>)}<aside>Whatever brought grief into your life, your loss does not need to look like someone else’s to deserve support.</aside></div></div></section>
<section className="grief-expect"><div className="grief-wrap"><h2 className="center">What to Expect</h2><div className="steps">{[['01','Connect','Reach out and request an appointment.'],['02','Be Heard','Share your loss and what life has been like since things changed.'],['03','Process','Explore emotions, memories, concerns, and everyday impact.'],['04','Move at Your Pace','Develop ways to cope, adjust, reconnect, and move forward.']].map(([n,h,p])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
<section className="grief-faq"><div className="grief-wrap faq-grid"><aside><h2>Questions About<br/>Grief & Loss Counseling</h2><p>Find answers to common questions about grief counseling and what to expect.</p></aside><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<b>＋</b></summary><p>{a}</p></details>)}</div></div></section>
<section className="grief-final"><div className="grief-wrap final-grid"><div><h2>Take the Time You Need.<br/>We’ll Meet You Where You Are.</h2><p>When you’re ready to talk, Open Arms Initiative is here to listen.</p></div><Link href="/contact" className="grief-btn">Request an Appointment　⌁</Link><div className="final-leaf">❧</div></div></section>
</main>}
