export const serviceCategories = {
  'Counseling & Therapy': {
    heading: 'Counseling & Therapy Services',
    links: [
      { name: 'Child & Adolescent Counseling', slug: 'child-adolescent-counseling', href: '/child-counseling-services-oklahoma-city/' },
      { name: 'Adult & Individual Counseling', slug: 'adult-counseling', href: '/adult-counseling-oklahoma-city/' },
      { name: 'Marriage & Couples Therapy', slug: 'marriage-couples-therapy', href: '/marriage-counseling-oklahoma-city/' },
      { name: 'Foster Care & Adoption Counseling', slug: 'foster-care-adoption-counseling', href: '/foster-care/' },
      { name: 'Grief and Loss Counseling', slug: 'grief-loss-counseling', href: '/grief-counseling-oklahoma-city/' },
      { name: 'Family Counseling', slug: 'family-counseling', href: '/family-therapy-oklahoma-city/' },
      { name: 'Depression & Anxiety Counseling', slug: 'depression-anxiety-counseling', href: '/depression-anxiety-counseling-oklahoma/' },
      { name: 'Family Support', slug: 'family-support', href: '/family-support-services-oklahoma-city/' },
      { name: 'Parent Support', slug: 'parent-support', href: '/parenting-classes-okc/' },
      { name: 'Local Referrals', slug: 'local-referrals', href: '/local-referrals/' },
    ],
    sideTitle: 'Trusted Team',
    sideLinks: [
      { name: 'About Us', href: '/about' },
      { name: 'Local Referrals', href: '/local-referrals/' },
      { name: 'FAQ', href: '/faq' },
    ],
    image: '/images/first.png',
  },
  // Hidden for now — restore this entry to bring "Clinical Training & Workshops" back to the nav.
  // 'Clinical Training & Workshops': {
  //   heading: 'Clinical Training & Workshops',
  //   links: [
  //     { name: 'Trauma-Informed Care Training', slug: 'trauma-informed-care-training' },
  //     { name: 'Mental Health Awareness & Human Development', slug: 'mental-health-awareness' },
  //     { name: 'Parenting Skills Development', slug: 'parenting-skills-development' },
  //     { name: 'Anxiety, Depression, and Stress Management', slug: 'anxiety-depression-stress-management' },
  //   ],
  //   sideTitle: 'Locations',
  //   sideLinks: [{ name: 'Oklahoma City', href: '/location' }],
  //   image: '/images/third.png',
  // },
  'Non-Profit': {
    heading: 'Non-Profit Services',
    links: [
      { name: 'Community Outreach & Support Programs', slug: 'community-outreach-support' },
      { name: 'Pro Bono Therapy Services', slug: 'pro-bono-therapy', href: '/pro-bono-counseling-okc/' },
    ],
    sideTitle: 'Social',
    sideLinks: [
      { name: 'Facebook', href: 'https://www.facebook.com/people/Open-Arms-Initiative/61570443695509/', external: true },
      { name: 'Instagram', href: 'https://www.instagram.com/openarms_initiative/', external: true },
      { name: 'Youtube', href: 'https://www.youtube.com/watch?v=IkwbPsOvdHU', external: true },
    ],
    image: '/images/4th.png',
  },
};

export const trainingSpeakingMenu = {
  heading: 'Training & Speaking',
  links: [
    { name: 'Trauma & Mental Health Training', slug: 'trauma-mental-health-training', href: '/training-speaking/trauma-mental-health-training' },
    { name: 'Jamie James, LPC', slug: 'jamie-james', href: '/training/jamie-james' },
    { name: 'Churches & Faith-Based Training', slug: 'churches-faith-based-training', href: '/services/churches-faith-based-training' },
    { name: 'Corporate & Business Training', slug: 'corporate-business-training', href: '/corporate-business-training' },
    { name: 'School Staff & Educator Training', slug: 'school-staff-educator-training', href: '/services/school-staff-educator-training' },
  ],
  sideTitle: 'Info',
  sideLinks: [
    { name: 'About Us', href: '/about-us' },
    { name: 'Location', href: '/location' },
    { name: 'Careers', href: '/careers' },
    { name: 'FAQ', href: '/faq' },
  ],
  image: '/images/second.png',
};

export const allServices = [
  {
    slug: 'child-adolescent-counseling',
    title: 'Child & Adolescent Counseling',
    category: 'Counseling & Therapy',
    summary: 'Specialized therapy helping children and teens process trauma, manage emotions, and navigate developmental challenges in a safe environment.',
    benefits: [
      'Trauma-informed child care',
      'Emotional regulation and coping strategies',
      'Behavioral improvement at home and school',
      'Strengthening parent-child communication',
    ],
    details: 'Our child and adolescent counseling programs provide a safe, nurturing space where young individuals can process complex emotions. Utilizing play therapy, cognitive behavioral techniques, and family engagement, our licensed therapists help children heal from past trauma, reduce anxiety, and build resilience.',
    image: '/images/5th.jpg',
  },
  {
    slug: 'adult-counseling',
    title: 'Adult & Individual Counseling',
    category: 'Counseling & Therapy',
    summary: 'Comprehensive therapy designed for adults dealing with life pressure, relationship issues, burnout, and mental health challenges.',
    benefits: [
      'Stress and burnout relief',
      'Relationship and boundary building',
      'Emotional healing from past experiences',
      'Actionable mental health toolkits',
    ],
    details: 'Adult counseling focuses on the complex challenges faced in adulthood, from career burnout and caregiver fatigue to deep-seated relational patterns. We provide evidence-based therapeutic care to help you restore emotional balance.',
    image: '/images/7th.jpg',
  },
  {
    slug: 'marriage-couples-therapy',
    title: 'Marriage & Couples Therapy',
    category: 'Counseling & Therapy',
    summary: 'Guiding partners toward healthier communication, deeper emotional intimacy, conflict resolution, and mutual understanding.',
    benefits: [
      'Rebuilding trust and connection',
      'Constructive conflict resolution methods',
      'Improved intimacy and emotional expression',
      'Pre-marital and marital alignment',
    ],
    details: 'Couples therapy helps partners identify unhelpful relationship dynamics, express emotional needs constructively, and work together toward a shared vision for their partnership.',
    image: '/images/8th.jpg',
  },
  {
    slug: 'foster-care-adoption-counseling',
    title: 'Foster Care & Adoption Counseling',
    category: 'Counseling & Therapy',
    summary: 'Trauma-informed guidance and emotional support for foster youth, adoptive children, foster parents, and adoptive families.',
    benefits: [
      'Specialized adoption & foster trauma care',
      'Support for attachment and bonding',
      '24/7 foster parent support systems',
      'Navigating placement transitions smoothly',
    ],
    details: 'Foster care and adoption bring unique emotional rewards and complex attachment dynamics. Our team provides specialized care to help families navigate transition phases, attachment security, and trauma recovery.',
    image: '/images/5th.jpg',
  },
  {
    slug: 'grief-loss-counseling',
    title: 'Grief and Loss Counseling',
    category: 'Counseling & Therapy',
    summary: 'Compassionate support for individuals navigating the loss of a loved one, life transition grief, or sudden life changes.',
    benefits: [
      'Safe space for processing loss',
      'Understanding stages of grief',
      'Building healthy remembrance mechanisms',
      'Reducing feelings of isolation',
    ],
    details: 'Grief affects every individual differently. Our grief counselors provide gentle guidance through the grieving process, helping you find strength and meaning while honoring your loss.',
    image: '/images/6th.jpg',
  },
  {
    slug: 'family-counseling',
    title: 'Family Counseling',
    category: 'Counseling & Therapy',
    summary: 'Therapies tailored to resolve familial tension, foster open dialog, rebuild trust, and support overall household well-being.',
    benefits: [
      'Better family communication patterns',
      'Conflict de-escalation strategies',
      'Strengthening family unity',
      'Support during major life shifts',
    ],
    details: 'Family counseling addresses relational dynamics as a unit, fostering empathy between members and establishing healthy boundary systems for a thriving home environment.',
    image: '/images/7th.jpg',
  },
  {
    slug: 'depression-anxiety-counseling',
    title: 'Depression & Anxiety Counseling',
    category: 'Counseling & Therapy',
    summary: 'Targeted therapeutic intervention utilizing CBT and mindfulness to alleviate debilitating anxiety and depressive symptoms.',
    benefits: [
      'Reduction of panic and chronic anxiety',
      'Mindfulness and grounding practices',
      'Restoring hope and daily motivation',
      'Symptom management strategies',
    ],
    details: 'Depression and anxiety can feel overwhelming, but with structured evidence-based care, recovery is achievable. We empower clients with practical, everyday strategies to regain confidence.',
    image: '/images/8th.jpg',
  },
  {
    slug: 'churches-faith-based-training',
    title: 'Churches & Faith-Based Training',
    category: 'Speaking & Training Engagements',
    summary: 'Empowering ministry leaders and faith communities with trauma-informed awareness and mental health crisis response tools.',
    benefits: [
      'Faith-friendly trauma training',
      'Equipping lay leaders & volunteers',
      'Crisis intervention strategies',
      'Destigmatizing mental health in ministry',
    ],
    details: 'We partner with church leaders and faith organizations to provide specialized workshops that bridge spiritual support with clinical mental health insights.',
    image: '/images/second.png',
  },
  {
    slug: 'corporate-business-training',
    title: 'Corporate & Business Training',
    category: 'Speaking & Training Engagements',
    summary: 'Workplace mental health workshops, stress management seminars, and empathetic leadership training for modern organizations.',
    benefits: [
      'Improving workplace mental well-being',
      'Burnout prevention for teams',
      'Empathetic leadership development',
      'Customized corporate sessions',
    ],
    details: 'A healthy workforce produces strong outcomes. Our business training equips managers and employees with actionable stress mitigation and resilience techniques.',
    image: '/images/third.png',
  },
  {
    slug: 'school-staff-educator-training',
    title: 'School Staff & Educator Training',
    category: 'Speaking & Training Engagements',
    summary: 'Equipping teachers, counselors, and school administration with trauma-informed classroom strategies for student success.',
    benefits: [
      'Recognizing childhood trauma signals',
      'Classroom de-escalation methods',
      'Educator self-care & stress management',
      'Fostering supportive learning environments',
    ],
    details: 'Educators are often the first to see signs of trauma or emotional distress in youth. We provide practical tools to turn classrooms into safe learning havens.',
    image: '/images/first.png',
  },
  {
    slug: 'trauma-informed-care-training',
    title: 'Trauma-Informed Care Training',
    category: 'Clinical Training & Workshops',
    summary: 'Comprehensive training for clinicians, care providers, and human service workers to deliver empathetic, trauma-sensitive care.',
    benefits: [
      'Deep understanding of trauma neuroscience',
      'De-escalation and safety planning',
      'Mitigating secondary traumatic stress',
      'Best practices in clinical care',
    ],
    details: 'Designed for professionals, our trauma-informed workshops cover foundational and advanced concepts in trauma recovery, attachment, and neurobiology.',
    image: '/images/third.png',
  },
  {
    slug: 'mental-health-awareness',
    title: 'Mental Health Awareness & Human Development',
    category: 'Clinical Training & Workshops',
    summary: 'Educational workshops highlighting developmental milestones, behavioral health awareness, and early intervention tactics.',
    benefits: [
      'Understanding human development stages',
      'Early detection of mental health issues',
      'Community education & advocacy',
      'Interactive learning modules',
    ],
    details: 'Promoting community awareness breaks down stigma and encourages early care. This workshop provides clear insights into mental health and human growth stages.',
    image: '/images/second.png',
  },
  {
    slug: 'parenting-skills-development',
    title: 'Parenting Skills Development',
    category: 'Clinical Training & Workshops',
    summary: 'Practical parenting courses focusing on positive discipline, emotional connection, trauma responsiveness, and child nurture.',
    benefits: [
      'Positive discipline techniques',
      'Strengthening parent-child bonds',
      'Managing difficult behaviors constructively',
      'Parental confidence building',
    ],
    details: 'Parenting can be challenging. Our courses equip parents with modern, trauma-aware discipline and communication skills to create a harmonious home.',
    image: '/images/first.png',
  },
  {
    slug: 'anxiety-depression-stress-management',
    title: 'Anxiety, Depression, and Stress Management',
    category: 'Clinical Training & Workshops',
    summary: 'Interactive group workshops providing practical toolkits to identify triggers, regulate stress, and build daily mental resilience.',
    benefits: [
      'Hands-on stress reduction techniques',
      'Cognitive reframing practices',
      'Building lifestyle wellness routines',
      'Group peer support and sharing',
    ],
    details: 'Learn actionable techniques to manage everyday stress, alleviate anxiety triggers, and maintain mental clarity through engaging clinical workshops.',
    image: '/images/third.png',
  },
  {
    slug: 'community-outreach-support',
    title: 'Community Outreach & Support Programs',
    category: 'Non-Profit',
    summary: 'Initiatives bringing free mental health education, family support resources, and community care to underserved Oklahoma communities.',
    benefits: [
      'Accessible community resources',
      'Workshops in local OKC neighborhoods',
      'Collaborative care networks',
      'Support for vulnerable families',
    ],
    details: 'Our non-profit outreach programs bring mental health awareness, resource navigation, and family support directly into local Oklahoma communities.',
    image: '/images/4th.png',
  },
  {
    slug: 'pro-bono-therapy',
    title: 'Pro Bono Therapy Services',
    category: 'Non-Profit',
    summary: 'No-cost counseling services ensuring quality mental health care remains accessible to low-income families and individuals in need.',
    benefits: [
      'Zero financial cost for qualifying clients',
      'Equal access to licensed therapists',
      'Comprehensive trauma & individual care',
      'Removing financial barriers to health',
    ],
    details: 'We believe access to quality mental healthcare is a right, not a privilege. Our pro-bono counseling initiative delivers compassionate care to families in financial hardship.',
    image: '/images/7th.jpg',
  },
];
